name    'AlexCline-reboot_required'
version '0.0.1'
author 'Alex Cline <alex.cline@gmail.com>'
license 'Apache License, Version 2.0'
summary 'A Puppet module for scheduling reboots of systems with pending updates.'
description 'A Puppet module for scheduling reboots of systems with pending updates.'
project_page 'https://github.com/AlexCline/reboot_required'
